version: '3.8'
services:
  mongodb:
    image: mongo:6.0.6
    container_name: mongodb
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1212312
      - MONGO_INITDB_DATABASE=doc
